### ISSUE TITLE
Deps are not installed

### ISSUE THREAD

**Issue by latot** [tsuyoshicho/action-mypy#112]
Hi, I try to use the actual action to perform the mypy one, but it didn't works because the actual setup does not install the packages deps, are least no with a pure ```pyproject.toml```, which means there is no ```requirements.txt```.

```
name: reviewdog
on: [pull_request]
jobs:
  mypy:
    name: runner / mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tsuyoshicho/action-mypy@v3
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with warning.
          level: warning
          # Change the current directory to run mypy command.
          # mypy command reads setup.cfg or other settings file in this path.
          workdir: src
```

```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "test"
version = "01.23.01.2024"
dependencies = [
  "pandas",
  "pandas-stubs",
  "pyarrow", #https://github.com/pandas-dev/pandas/issues/54466
  "sqlalchemy",
  "scipy",
  "numpy",
  "matplotlib",
  "mypy"
]
description = "spam spam!"
readme = "README.md"
```

I got similar to this ones:
```
Library stubs not installed for "pandas" [import-untyped]
```

Thx!
