### ISSUE TITLE
Type checking with third party packages

### ISSUE THREAD

**Issue by auscompgeek** [tsuyoshicho/action-mypy#16]
I have a project with multiple dependencies from PyPI. How can I use this such that mypy will find my dependencies? Installing into the virtualenv provided by `actions/setup-python@v2` doesn't help.

**Comment by tsuyoshicho** [comment]
Nnn...

@auscompgeek , your requirements.txt need mypy install.

Type below with your develop environment,

```
$ whiech -a mypy
```

If work do so OK. return executable path.

And then, GitHub workflow setup and other setting equals to your local develop environment.

CI env is isolated. that's mean direct install OK (not need virutalenv).

Like this.

```
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.9' ]
    name: Python ${{ matrix.python-version }} test
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: pip install -r requirements.txt
      - uses: tsuyoshicho/action-mypy@v2
```
