### ISSUE TITLE
Multiple reviews generated for multiline mypy error

### ISSUE THREAD

**Issue by abelcheung** [tsuyoshicho/action-mypy#38]
I'm using action with following step configuration:

```yaml
    - name: Mypy review
      uses: tsuyoshicho/action-mypy@v3
      with:
        reporter: github-pr-review
        level: warning
        fail_on_error: true
```

As an example, following is a multi-line `mypy` error when overriding superclass property in an incompatible way:

    /home/runner/.../file.pyi:28:6: error: Signature of "error_log" incompatible with supertype "_Validator"
    /home/runner/.../file.pyi:28:6: note:      Superclass:
    /home/runner/.../file.pyi:28:6: note:          def error_log(self) -> _ErrorLog
    /home/runner/.../file.pyi:28:6: note:      Subclass:
    /home/runner/.../file.pyi:28:6: note:          @overload
    /home/runner/.../file.pyi:28:6: note:          def error_log(self) -> int
    /home/runner/.../file.pyi:29:5: error: Return type "int" of "error_log" incompatible with return type "_ErrorLog" in supertype "_Validator"

The error came from a single diff hunk, so I was expecting a single reviewdog action. Instead, it generated 7 independent reviews on the same pull request, each containing one line, and all of them are attached to the same diff.
