### ISSUE TITLE
Custom MyPy binary

### ISSUE THREAD

**Issue by jonathanberthias** [tsuyoshicho/action-mypy#66]
When installing dependencies with Poetry, the `mypy ...` command is not available and instead one should use `poetry run mypy ...`.

It would be nice to be able to add an option for the binary used [for the mypy invocation](https://github.com/tsuyoshicho/action-mypy/blob/master/script.sh#L38) (and potentially an option to skip installing mypy without checking if it is installed).

**Comment by tsuyoshicho** [comment]
I will consider responding this issue.

**Comment by tsuyoshicho** [comment]
@jonathanberthias san,

Fix action-mypy for using "Poetry".
https://github.com/tsuyoshicho/action-mypy/tree/feature/adaptivesetup

Could you please test this branch?

```yaml
      - uses: tsuyoshicho/action-mypy@feature/adaptivesetup
        with:
          # your settings
          # ...
          # Poetry support
          execute_command: 'poetry run mypy'
          setup_method: 'nothing'
```

(Also check the README.)
