### ISSUE TITLE
Read mypy arguments from config file

### ISSUE THREAD

**Issue by vnmabus** [tsuyoshicho/action-mypy#9]
It appears that mypy arguments in setup.cfg are not read. As a result, the action reports different errors than executing mypy locally.

**Comment by tsuyoshicho** [comment]
Thanks report.

I inv. it.

**Comment by tsuyoshicho** [comment]
Mr @vnmabus ,

Create test branchs.

- with setup.cfg https://github.com/tsuyoshicho/action-test-repo/pull/11
- without setup.cfg https://github.com/tsuyoshicho/action-test-repo/pull/12

Test code as same.

setup.cfg see below:

```ini:setup.cfg
[mypy]
warn_no_return = False
```

with setup.cfg test do no report `Missing return statement`.
That's fine.

As far as the results are concerned, it reads setup.cfg and works correctly.

Please your action-mypy setting (`filter-mode`, `mypy_flags`...) to check in workflow what you needed.

**Comment by vnmabus** [comment]
I still do not get what I am doing wrong.

I have this PR: https://github.com/GAA-UAM/scikit-fda/pull/296
In the setup.cfg I have set the option `implicit_reexport ` for mypy, and it works locally.
However action-mypy is still reporting `Module '...' has no attribute '...'` errors.

The code for the workflow is
```
name: Mypy

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
    - uses: actions/checkout@v2
    - uses: tsuyoshicho/action-mypy@v1
      with:
        github_token: ${{ secrets.github_token }}
        # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
        reporter: github-pr-review
        # Change reporter level if you need.
        # GitHub Status Check won't become failure with warning.
        level: warning
```
