### ISSUE TITLE
Suggestion: Allow user to choose mypy version manually

### ISSUE THREAD

**Issue by abelcheung** [tsuyoshicho/action-mypy#94]
Sometimes people may not want to use the latest `mypy` for testing, because `mypy` can change its type checking output format (for example, `Tuple[...]` is changed to `tuple[...]` in 1.4, and `Union[a, b]` becomes `a | b`) . People who run automatic test suite would want to pin to a very specific `mypy` version.

Indeed, it is possible to pin to a specific `action-mypy` commit in GitHub workflow instead, but that also means people are unable to use any new features in latest `action-mypy`.

To be concise, I mean something like:

```yaml
- name: workflow name
  uses: tsuyoshicho/action-mypy@v3
  with:
    mypy_version: '1.2.0'
```
